server:
  port: 9191
  
spring:
  application:
    name: API-GATEWAY 
  
  cloud:
    gateway:
      routes:
        - id: CUSTOMER-SERVICE
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customer/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: CUSTOMER-SERVICE
#                fallbackuri: forward:/customerServiceFallBack
#          
        - id: WASHER-SERVICE
          uri: lb://WASHER-SERVICE
          predicates:
            - Path=/washers/** 
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: WASHER-SERVICE
#                fallbackuri: forward:/washerServiceFallBack
#                

        
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream
#        



##Circuit Breaker other approach


#resilience4j:
#  circuitbreaker:#    instances:
#      userService:
#        register-health-indicator: true
#        event-consumer-buffer-size: 10
#        automatic-transition-from-open-to-half-open-enabled: true
#        failure-rate-threshold: 50
#        minimum-number-of-calls: 5
#        permitted-number-of-calls-in-half-open-state: 3
#        sliding-window-size: 10
#        wait-duration-in-open-state: 5s
#        sliding-window-type: COUNT_BASED
#        
#management:
#  health:#    circuitbreakers:#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: health
#  endpoint:
#    health:
#      show-details: always



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost